# Generated by Django 4.0.6 on 2022-08-02 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('image2', models.ImageField(blank=True, upload_to='products/images/')),
                ('image3', models.ImageField(blank=True, upload_to='products/images/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Jacket', 'Jacket'), ('Shirt', 'Shirt'), ('T-shirt', 'T-shirt'), ('Bag', 'Bag'), ('Glasses', 'Glasses'), ('Others', 'Others')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
