# Generated by Django 4.0.6 on 2022-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler_app', '0003_alter_add_product_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
