# Generated by Django 4.0.6 on 2022-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='descripation',
            field=models.CharField(max_length=1550),
        ),
    ]
