# Generated by Django 4.0.6 on 2022-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
