# Generated by Django 4.0.6 on 2022-08-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_blogs_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='Blogger_Profile')),
                ('profession', models.CharField(max_length=255)),
                ('github', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
            ],
        ),
    ]
