# Generated by Django 4.0.6 on 2022-08-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_blogger_profile_delete_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogger_profile'),
        ),
    ]
